### ISSUE TITLE
Google button doesn't appear only few users

### ISSUE THREAD

**Issue by cesoriano** [mouneyrac/moodle-auth_googleoauth2#113] opened 2015-04-27 10:01 UTC
I don't know why but two users can't see google button in my login page when the rest of the people(minimun 58 is inside in this moment) can see without problems.

Two users with problems use Google Chrome

**Comment by mouneyrac** [comment] 2015-05-15 09:29
Is it what they say to you? What is their exact URL? Hard to reproduce with so few details ;)

**Comment by mouneyrac** [comment] 2015-05-29 06:31
I close the issue cesoriano as you may have fixed your problem since you reported this issue. Feel free to comment if it is not the case. I also think it may not be related to the plugin. Let us know how you resolved your problem thought (it can always help people with the same problem).
Cheers.

**Closed by mouneyrac** 2015-05-29 06:31 UTC
Labels: Help me
