### ISSUE TITLE
googleoauth2/faileduserdetails

### ISSUE THREAD

**Issue by frumbert** [mouneyrac/moodle-auth_googleoauth2#146] opened 2015-08-04 04:55 UTC
I dropped the plugin in, activated it, and tried setting up with Google using the instructions on the plugin. Attempting a sign-in results in the error:

    googleoauth2/faileduserdetails

I can't see anything on the google dashboard that tells me why it's failing, and the error in the plugin tries to redirect to the missing page https://docs.moodle.org/29/en/error/auth_googleoauth2/faileduserdetails.

**Comment by mouneyrac** [comment] 2015-08-04 06:58
Hello Tim,
which version do you use?

**Comment by frumbert** [comment] 2015-08-04 09:21
Moodle 2.9.1 build 2015051101.03
$plugin->version  = 2015051504;

**Comment by mouneyrac** [comment] 2015-08-04 09:49
which provider are you testing? how do you set it up?

**Comment by mouneyrac** [comment] 2015-08-04 09:50
do you have debug mode turn on in Moodle?

**Comment by frumbert** [comment] 2015-08-04 10:48
Ok so this is wierd. I added

$CFG->debug = 32767;
$CFG->debugdisplay = true;

to my config.php and loaded up again, this time in incognito mode (chrome) to get a different session, and it has worked.

Removing the debug switch again and it still works. Perhaps there’s a glitch somehow during the very first pass when I’m authorizing google to grant rights or something? I’ll try a few more times after resetting some things and see if I can grab a proper error stack using debug. I’ve poked around in the error log and can’t see anything abnormal around the time I got the error, so perhaps it’s a non-error / one-time glitch.

Cheers,
Tim

**Comment by grwinner** [comment] 2015-08-11 19:29
This workes for me also in the same situation

**Comment by andrebonner** [comment] 2015-08-18 12:40
I recently updated the OAUTH plugin and I noticed that my users aren't able to sign in. Attempting a sign-in results in the error:

googleoauth2/faileduserdetails

I tried the debug code and I still received the same error plus debug information. I am using $version  = 2014051201.00
$release  = '2.7.1 (Build: 20140714)'

Please help!

**Comment by maliky** [comment] 2015-08-20 15:32
J'aimerai bien le faire fonctionner se plugin mais jusqu'à présent je n'ai pas pu répéter les fois où il a marché.

**Comment by maliky** [comment] 2015-08-20 15:47
After entering facebook credential I'm forwarded to a page with googleoauth2/faileduserdetails
plateforme : debian wheezy
Moodle: Moodle 2.9.1+ (Build: 20150813)
googleauth2: 

here is the devel stack trace
$a contents:
Stack trace:

    line 175 of /auth/googleoauth2/auth.php: moodle_exception thrown
    line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

**Comment by maliky** [comment] 2015-08-20 15:53
googleoauth2 Build: 2015051504

**Comment by mouneyrac** [comment] 2015-08-27 07:29
Anyone still having the faileduserdetails issue?

Anyone still having the issue can confirm that the version he is using is the correct branch, ie STABLE_XX matching MOOLDE_XX_STABLE? Knowing there is a STABLE_25, STABLE_26 then any more recent Moodle site should use the plugin master branch. Also confirm that you are using the lastest code and you still having the issue. Then turn debug on, and post here the full error message with debug info.

Finally anyone having fixed the issue and want to explain how (s)he did?

**Comment by mouneyrac** [comment] 2015-08-27 07:33
actually re-reading frumbert (Tim) and grwinner said it worked for them. So only maliky and andrebonner (Andre) are left with the issue. I'll come back to you :)

**Comment by maliky** [comment] 2015-08-27 12:58
I'm really not a expert in git but I managed to pull googleauth2 and moodle to there latest stable version I think.
Moodle 2.9.1+ (Build: 20150820)
Googleauth2 2.0 (Build: 2015051504)

Maybe we could meet on irc.  What time are you usualy there ? malik aka jil on freenode

**Comment by maliky** [comment] 2015-08-29 18:57
I really don't get what I did wrong ?
I checked that I had used git to pull the latest version of googleauth2.  Apparently I did not use git for googleauth2 (I did for moodle)
So I did the following :
git clone https://github.com/mouneyrac/moodle-auth_googleoauth2.git
mv moodle-auth_googleoauth2/ googleoauth2
cd googleoauth2/
git branch --track MYGOOGLEAUTH2_S26 remotes/origin/STABLE_26
git checkout MYGOOGLEAUTH2_S26

but returning to moodle, I am being told that the previous version is newer than the git pulled one.  I'm surprised.  It says current version 2015051504 	(as indicated in previous post)  and new version (the one with git pull) version 2014111902.

What am I not doing right ?

partly because of this plugin I upgraded from a shared hosting to a VPS.  I would  really like to have it work for this school year starting in a few days.  Wasted last year already, and some of the previous year too.  When I think about it I say Wouaou... It's because I'm in ivory coast I cannot attend moodle moot or other moodle gathering.  I'm one of the few using moodle here and I doubt that other people here could help me.  I'm the one suppose to help them, and I can at least with Moodle base admin.

S'il te plait aides moi. si possible via skype.  la mardi prochain je reprends mon boulot (prof de math) et j'aurais moins de temps.

Thanks you.

**Comment by mouneyrac** [comment] 2015-08-30 13:54
If you are using Moodle 2.8 then you need to take master branch not STABLE_26

**Comment by maliky** [comment] 2015-08-30 18:16
When are you on irc mouneyrac ?  

I 
git branch --track MYGOOGLEOAUTH_LATEST remotes/origin/master
git checkout MYGOOGLEOAUTH_LATEST
chown www-data -R .
reloaded the plugin admin page.  and I'm (nearly) back to where I was when I installed googleauth2 from moodle plugin directory.  nearly because now I can git pull any changes :o)  thank you.

But still the error faileduserdetails is still there.
What does it mean exactly ? by the way.  Where is it fired from ? why ?

**Comment by maliky** [comment] 2015-08-30 18:17
I have one user who authentified using this googleoauth2 probably me a long time ago with a test account.  But where can I see all users using this authentification method ?
I want identify him to remove him and try again.

**Comment by maliky** [comment] 2015-08-30 18:55
Could I have a userconflict with another moodle account using the same email adresse ?

After updated and addition of linked's credential Here's the result of my attemps to login.
with linked in
Debug info:
Error code: couldnotauthenticateuserlogin
Stack trace:

    line 374 of /auth/googleoauth2/auth.php: moodle_exception thrown
    line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

with  google
Debug info:
Error code: invalidstateparam
$a contents:
Stack trace:

    line 76 of /auth/googleoauth2/lib.php: moodle_exception thrown
    line 19 of /auth/googleoauth2/google_redirect.php: call to googleoauth2_provider_redirect()

and with facebook
Debug info:
Error code: faileduserdetails
$a contents:
Stack trace:

    line 175 of /auth/googleoauth2/auth.php: moodle_exception thrown
    line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

-----------------------
are my ip blacklisted because of my geographical situation?

**Comment by maliky** [comment] 2015-08-30 19:02
also, I losted the pictures for the links.  I wouldn't minde going under the hood but we need to talk this on irc.

**Comment by mouneyrac** [comment] 2015-08-31 04:39
Maliky can you check if it at least work on a fresh install of Moodle and the plugin?
I did a presentation on the imoot: https://www.youtube.com/watch?v=55gpCSnd1yU
I don't like to give this link too much as I would prefer to redo a new one shorter and better but for the moment that the only demo video I have made.

**Comment by maliky** [comment] 2015-08-31 11:34
I'm started to think it's not my fault.
Fresh moodle install with latest stable release gitted.  I installed the plugin
The website is at http://classe.numerique.ci

I created new web app for google, facebook and linked and entered the new credentials in googleauth2 settings.

But still
when trying to login in google I give my consent and then :
auth_googleoauth2/faileduserdetails

More information about this error

Debug info: 
Error code: faileduserdetails
$a contents:
Stack trace:
line 175 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

when trying to login in facebook I give my consent and then :

Authentication method error.
Please try to login again with your username and password.

Try again.
Forgot your password?

More information about this error

Debug info: 
Error code: couldnotauthenticateuserlogin
Stack trace:
line 374 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

when trying to login in linkedin I give my consent and then :

Authentication method error.
Please try to login again with your username and password.

Try again.
Forgot your password?

More information about this error

Debug info: 
Error code: couldnotauthenticateuserlogin
Stack trace:
line 374 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

For each I was already logged in so It's not a password problem.
It could be that each of these account use the same email adress.
I don't know.  Need help.

**Comment by mouneyrac** [comment] 2015-08-31 12:12
Thanks for sharing your link maliky, I tested all provider on your site:

linkedin => it works
facebook => it doesn't work because your are using a development app, you need to setup facebook properly (I don't remember if I explain that in the settings page, if not it is probably a new requirement - oauth2 setup have a big tendency to change over the time on each providers, it is why that often the explanation need to be updated - sometimes the api itself changes and it is probably why google fail for you)
google => it fails. I am pretty sure it is because you didn't enable the Google+ api as mentioned on the settings page (the error mention fail to get user details - it is likely to be the cause)

Globally you succeded to setup the plugin. You just miss to enable Google+ API (see the doc) and production mode on facebook (see the doc, if it is not explain, then go through the facebook admin pages or google it, it should be pretty obvious that your setup is in dev mode)

Let me know if all got solve.

PS: yes you are not allowed to login with googleoauth2 authentication method if your user has already the email address used by manual auth method. There is an issue for allowing some kind of hack and bypass the Moodle check. I will implement that later.

**Comment by mouneyrac** [comment] 2015-08-31 12:15
So globably, to answer the original issue, I am pretty sure it is related to the fact that people didn't enable the Google+ API (as mentioned in the settings page). Anyway it is good reports, I will improve the error message so it gives some clues to people. Thanks all for your feedbacks!

**Comment by maliky** [comment] 2015-08-31 14:29
ok I will check again but i had notice the dev mode in facebook. it is
activated by default for new apps maybe i forgot to disable it this time.
as for hoogle api.  i ve been reading the docs for quite a long time. more
that the info you give in the settings since the info wher not there first.

I m puzzled about what to do now.  I even personalised the validation
screen for numerique.ci.  may be  you could try there and tell me if it
fails too.

as for me i need to try linked in with a different email as you say it will
conflict with the admin one.

You are not answering my question about irc.  is it impossible ?

Malik Koné,
envoyé depuis Abidjan avec un mobile
Le 31 août 2015 12:15, "Jérôme Mouneyrac" <notifications@github.com> a
écrit :

**Comment by maliky** [comment] 2015-08-31 18:51
Ok, so I checked calmly and indeed I had forgotten to set the facebook app
to active and to enable the google+ api
I have successuly test facebook with firefox.  With chrome juste after
clicking the button it screams a fishing alerte. I guess it's because I did
not paye a ssl certificate for my site.

Now, I have checked for the previous google app linked to my full web site
ecole.numerique.ci and there I had not forgoten to activate the google+
api. Nevertheless removed useless api activation "google maps, video,
searh" and reactivated google+ api after desactivation.

For the facebook linked to the full web site, it was activtated too, but
so were other useless options like "native app ..."
I tested it after correction and  it works !

I could not test with google and linked since it requires three distinct
emails and I don't have those account ready now.

Thank you anyway for encouragements and your test.  Please, if you can
check if it works for you on ecole.numerique.ci for all three frameworks.


2015-08-31 14:15 GMT+02:00 Jérôme Mouneyrac <notifications@github.com>:

**Comment by mouneyrac** [comment] 2015-08-31 19:41
Hi maliky I tested your "official" site I can login with both Google and Facebook.

For the SSL issue I use cloudflare to manage my DNS. They offer free SSL support. It has the great advantage that you don't need to setup it on your server and their certificate is valid.

**Comment by mouneyrac** [comment] 2015-09-02 04:33
I just pushed a change that now mention to check that the Google+ API is enabled. I also now open the provider admin links in a new tab - it was annoying to go back. Finally I created a new issue for update facebook instructions has they changed again.

I am closing this issue as I believe I answer the initial problem. Thanks all for your feedback. If you have different issues, please open a new issue.

Also if you have some time, do not forget to, first, favorite the plugin on the Moodle.org page: https://moodle.org/plugins/view/auth_googleoauth2 and also stargize it on Github. It highly motivate me to climb the Moodle ladder: https://moodle.org/plugins/report/index.php?report=favourites

Thanks again and have a good day to everyone :)

**Closed by mouneyrac** 2015-09-02 04:33 UTC
Labels: Help me, ready

**Comment by maliky** [comment] 2015-09-02 06:06
Thank you.  it s all fixed for me. you do deserve  many moodle   star.

Malik Koné,
envoyé depuis Abidjan avec un mobile
Le 2 sept. 2015 04:33, "Jérôme Mouneyrac" <notifications@github.com> a
écrit :

**Comment by fmsabeti** [comment] 2015-09-04 15:01
Hi there,

First time poster, so please excuse any netiquette mistakes here. We're running Moodle 2.9 (Build: 20150511) and trying to use Google as our authentication through OAuth2 version 2.1 (Build: 2015090200). We're running into an error noted above, and when we try to authenticate, it opens the Google login window, but following login, returns to moodle with the error: auth_googleoauth2/invalidstateparam 

We have enabled Google+ API. Any other advice or help that you might have would be great!

Thanks!

**Comment by GitRaams** [comment] 2015-10-08 20:50
Hi All

A solution for the OAuth2 - Google - Error....in Moodle, in case you are encountering the above issue...!

Moodle --> Google --> Moodle using OAuth2..., I did get the same error above and trying for the last 24 hours. After finding no solutions...just went back to Moodle...and stumbled upon this setting...
that I had not enabled...(or actually it was at default, but when changed it worked. !!!).

In Moodle - user creation page ... below the "username" field, there is an option 
"Choose an authentication method" --> [Manual accounts] (The default value).

Change this value to "Oauth2".
Make sure, username and email-id fields are the same.

It works great now. Thanks for everyone for everything.

GitRaams! 
(created a user-id to provide this solution to the world that gave everything !!!)

**Comment by andrimuhyidin** [comment] 2017-03-28 01:52
Hello, i have same problem.

Authentication method error.
Please try to login again with your username and password.

Try again.
Forgot your password?

More information about this error

Any solution for this problem?

**Comment by andrimuhyidin** [comment] 2017-03-28 01:53
i login with GOOGLE ACCOUNT
