### ISSUE TITLE
Manual display of button showing link but not image

### ISSUE THREAD

**Issue by espertus** [mouneyrac/moodle-auth_googleoauth2#152] opened 2015-08-18 19:59 UTC
I added the prescribed line to `login/index_form.html` (previous line shown for context):

```
<h2><?php print_string("login") ?></h2>
<?php require_once($CFG->dirroot . '/auth/googleoauth2/lib.php'); auth_googleoauth2_display_buttons(); ?>
```
I unchecked "Display buttons on login page" on your settings page.

When I try logging in, I only see a link to use Google login, not the button:

![screenshot - 8_18_2015 12_52_52 pm](https://cloud.githubusercontent.com/assets/661056/9341041/49d17838-45a8-11e5-8462-a64fa1343119.png)

If I reenable "Display buttons on login page", I see the image twice:

![screenshot - 8_18_2015 12_57_54 pm](https://cloud.githubusercontent.com/assets/661056/9341143/f4dbb892-45a8-11e5-869d-d4e8e6cd0457.png)

I am using Moodle 2.9.1 and PHP 5.4.

Thank you.

**Comment by espertus** [comment] 2015-08-18 23:08
FYI, the button fails to show up in Chrome, Firefox, or Edge, in case you were wondering if it is browser-dependent.

**Comment by mouneyrac** [comment] 2015-09-05 04:37
Thanks Ellen,
can you check again with the latest code? I can not reproduce it.

 Note: even thought it is not what the issue is about, having more than once the Google button won't work The first button will generate a state code that will be overwritten by the second button.

**Comment by mouneyrac** [comment] 2015-11-04 13:41
As there are no more activities on this issue I will close it. Let us know if you found out what was your problem. Thanks.

**Closed by mouneyrac** 2015-11-04 13:41 UTC
Labels: Help me

**Comment by matcho** [comment] 2016-04-13 14:53
Hi.

With Chrome 49 on Mac, the "facebook" and "google" buttons (I only use those 2) don't appear, just as Ellen reported.
According to Chrome's inspector, the width and height of the link are both 0. Setting them to an arbitrary value is not enough though, still no buttons...

The buttons show as expected with Safari on the same machine, and with any other browser / OS combination we tried (at least Ubuntu, Windows 10 x Chrome, Firefox)

Thanks for any help, and thanks for your helpful plugin !
Cheers,
Mathias
